import type { ReactNode } from 'react';
import Link from 'next/link';
import { LandingHeader } from '@/components/layout/landing-header';
import { LandingFooter } from '@/components/layout/landing-footer';

export const metadata = {
  title: 'Privacy Policy — Paisa',
  description: 'Privacy Policy for Paisa personal finance management application.',
};

function Table({ headers, rows }: { headers: string[]; rows: (string | ReactNode)[][] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm text-muted-foreground border-collapse">
        <thead>
          <tr className="border-b border-white/10 dark:border-white/5">
            {headers.map((h) => (
              <th key={h} className="text-left py-2 pr-4 last:pr-0 font-semibold text-foreground">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-white/5">
          {rows.map((row, i) => (
            <tr key={i}>
              {row.map((cell, j) => (
                <td key={j} className="py-2 pr-4 last:pr-0 align-top">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Divider() {
  return <div className="w-full h-px bg-gradient-to-r from-transparent via-border to-transparent opacity-50" />;
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-premium-gradient dark:bg-premium-gradient-dark">
      <LandingHeader />
      <main className="container mx-auto px-6 lg:px-8 py-16 max-w-4xl">
        <div className="glass-morphism dark:glass-morphism-dark rounded-3xl p-8 lg:p-12 space-y-8">

          {/* Header */}
          <div className="space-y-1">
            <h1 className="text-3xl lg:text-4xl font-bold text-gradient-moonlight">Privacy Policy — Paisa</h1>
            <p className="text-muted-foreground text-sm"><span className="font-medium text-foreground">Last updated:</span> March 6, 2026</p>
            <p className="text-muted-foreground text-sm"><span className="font-medium text-foreground">App package:</span> com.aths7.paisav5</p>
          </div>

          <Divider />

          {/* 1. Introduction */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">1. Introduction</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paisa (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) is a personal finance management application. This Privacy Policy explains what data we collect, why we collect it, how it is stored, and your rights over it. By using the app, you agree to this policy.
            </p>
          </section>

          <Divider />

          {/* 2. Data We Collect */}
          <section className="space-y-6">
            <h2 className="text-xl font-semibold text-foreground">2. Data We Collect</h2>

            <div className="space-y-3">
              <h3 className="text-base font-semibold text-foreground">2.1 Account &amp; Identity Data</h3>
              <Table
                headers={['Data', 'Source', 'Purpose']}
                rows={[
                  ['Email address', 'You provide at registration', 'Account creation & login'],
                  ['Password', 'You provide at registration', 'Authentication (hashed by Firebase — we never see it in plain text)'],
                  ['Display name', 'You provide at registration or profile update', 'Personalising your experience'],
                  ['Profile photo', "You select from your device's photo library", 'Profile display'],
                  ['User ID (UID)', 'Auto-generated by Firebase', 'Linking your data internally'],
                  ['Account creation date', 'Auto-generated', 'Internal records'],
                ]}
              />
            </div>

            <div className="space-y-3">
              <h3 className="text-base font-semibold text-foreground">2.2 Financial Data</h3>
              <Table
                headers={['Data', 'Source', 'Purpose']}
                rows={[
                  ['Wallet name & icon', 'You provide', 'Organising your accounts'],
                  ['Transaction type (income/expense)', 'You provide', 'Categorising entries'],
                  ['Transaction amount', 'You provide', 'Financial tracking'],
                  ['Transaction date', 'You provide', 'Timeline and reporting'],
                  ['Expense category', 'You provide', 'Spending awareness'],
                  ['Transaction description', 'You provide (optional)', 'Personal notes'],
                  ['Receipt image', "You select from your device's photo library (optional)", 'Attaching proof of transaction'],
                ]}
              />
            </div>

            <div className="space-y-3">
              <h3 className="text-base font-semibold text-foreground">2.3 Device Data</h3>
              <Table
                headers={['Data', 'Source', 'Purpose']}
                rows={[
                  ['Authentication session token', 'Auto-generated by Firebase Auth', 'Keeping you logged in between sessions (stored via AsyncStorage on your device)'],
                ]}
              />
            </div>
          </section>

          <Divider />

          {/* 3. Data We Do NOT Collect */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">3. Data We Do NOT Collect</h2>
            <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-1">
              {[
                'Location data',
                'Contacts or address book',
                'Microphone or camera input',
                'SMS or call logs',
                'Device identifiers (IMEI, MAC address)',
                'Advertising IDs',
                'Browsing history',
                'Any data from other apps',
              ].map((item) => <li key={item}>{item}</li>)}
            </ul>
          </section>

          <Divider />

          {/* 4. How We Use Your Data */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">4. How We Use Your Data</h2>
            <p className="text-muted-foreground leading-relaxed">Your data is used solely to operate the app:</p>
            <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-1">
              <li><span className="font-medium text-foreground">Authentication</span> — verify your identity and keep you securely logged in</li>
              <li><span className="font-medium text-foreground">Financial tracking</span> — store and display your wallets, income, and expense transactions</li>
              <li><span className="font-medium text-foreground">Profile display</span> — show your name and photo within the app</li>
              <li><span className="font-medium text-foreground">App functionality</span> — enable all features (adding, editing, deleting transactions and wallets)</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              We do not use your data for advertising, profiling, or any purpose beyond operating the app for you personally.
            </p>
          </section>

          <Divider />

          {/* 5. Data Storage & Third-Party Services */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">5. Data Storage &amp; Third-Party Services</h2>
            <p className="text-muted-foreground leading-relaxed">Your data is stored using <span className="font-medium text-foreground">Google Firebase</span>, which includes:</p>
            <Table
              headers={['Firebase Service', 'What it stores']}
              rows={[
                [<span key="auth" className="font-medium text-foreground">Firebase Authentication</span>, 'Email, password hash, UID, display name'],
                [<span key="firestore" className="font-medium text-foreground">Firebase Firestore</span>, 'User profile, wallets, transactions'],
                [<span key="storage" className="font-medium text-foreground">Firebase Storage</span>, 'Profile photos, wallet icons, receipt images'],
              ]}
            />
            <p className="text-muted-foreground leading-relaxed">
              Additionally, uploaded images (profile photos, wallet icons, receipt images) are hosted via <span className="font-medium text-foreground">Cloudinary</span>.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Firebase is a Google LLC service. Data may be stored on Google servers outside your country. Google&apos;s Privacy Policy applies to these services.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <span className="font-medium text-foreground">AsyncStorage</span> stores your authentication session token locally on your device only.
            </p>
            <p className="text-muted-foreground leading-relaxed font-medium text-foreground">
              We do not sell, rent, or share your data with any other third parties.
            </p>
          </section>

          <Divider />

          {/* 6. Data Retention */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">6. Data Retention</h2>
            <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-1">
              <li>Your data is retained for as long as your account is active.</li>
              <li>If you delete your account, all associated data (profile, wallets, transactions, images) will be permanently deleted from Firebase.</li>
              <li>Authentication session data on your device is cleared on sign-out.</li>
            </ul>
          </section>

          <Divider />

          {/* 7. Permissions Requested */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">7. Permissions Requested</h2>
            <Table
              headers={['Permission', "Why it's needed"]}
              rows={[
                [<span key="internet" className="font-medium text-foreground">Internet</span>, 'Required to connect to Firebase (authentication, data sync)'],
                [<span key="photos" className="font-medium text-foreground">Photo Library (Read)</span>, 'Required to let you select a profile photo or attach receipt images to transactions'],
              ]}
            />
            <p className="text-muted-foreground text-sm">No other system permissions are requested.</p>
          </section>

          <Divider />

          {/* 8. Your Rights */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">8. Your Rights</h2>
            <p className="text-muted-foreground leading-relaxed">You have the right to:</p>
            <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-1">
              <li><span className="font-medium text-foreground">Access</span> your data at any time within the app</li>
              <li><span className="font-medium text-foreground">Update</span> your profile name and photo via the Profile screen</li>
              <li><span className="font-medium text-foreground">Delete</span> individual transactions or wallets at any time</li>
              <li><span className="font-medium text-foreground">Delete your account</span> — go to <span className="font-medium text-foreground">Profile → Settings → Delete Account &amp; Data</span> and all your data will be permanently erased</li>
            </ul>
          </section>

          <Divider />

          {/* 9. Children's Privacy */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">9. Children&apos;s Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paisa is not directed at children under the age of 13. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, please contact us and we will delete it promptly.
            </p>
          </section>

          <Divider />

          {/* 10. Contact */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">10. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">For privacy questions, data deletion requests, or any concerns:</p>
            <ul className="list-none text-muted-foreground leading-relaxed space-y-1">
              <li><span className="font-medium text-foreground">Email:</span> [your-contact-email@domain.com]</li>
              <li><span className="font-medium text-foreground">App:</span> Paisa (com.aths7.paisav5)</li>
            </ul>
          </section>

          <Divider />

          {/* 11. Changes to This Policy */}
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">11. Changes to This Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this policy as the app evolves. We will update the &ldquo;Last updated&rdquo; date at the top. Continued use of the app after changes constitutes acceptance.
            </p>
          </section>

          <Divider />

          {/* Play Store Data Safety Declaration */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">Play Store Data Safety Declaration</h2>
            <p className="text-muted-foreground leading-relaxed">
              When filling in the <span className="font-medium text-foreground">Data Safety</span> section in Google Play Console, declare the following:
            </p>
            <Table
              headers={['Data Type', 'Collected', 'Shared', 'Required', 'Can User Delete']}
              rows={[
                ['Name', 'Yes', 'No', 'Yes', 'Yes'],
                ['Email address', 'Yes', 'No', 'Yes', 'Yes'],
                ['User ID', 'Yes', 'No', 'Yes', 'Yes'],
                ['Profile photo', 'Yes', 'No', 'No (optional)', 'Yes'],
                ['Financial info (transactions)', 'Yes', 'No', 'Yes', 'Yes'],
                ['Photos / receipts', 'Yes', 'No', 'No (optional)', 'Yes'],
              ]}
            />
            <ul className="list-disc list-inside text-muted-foreground leading-relaxed space-y-1">
              <li>All data is <span className="font-medium text-foreground">encrypted in transit</span> (Firebase/Cloudinary handle this automatically via TLS)</li>
              <li>Data is <span className="font-medium text-foreground">not used for tracking</span> or advertising</li>
              <li>Users can request deletion via the in-app &ldquo;Delete Account &amp; Data&rdquo; feature</li>
            </ul>
          </section>

          <Divider />

          <div className="pt-2">
            <Link
              href="/"
              className="text-primary hover:text-primary/80 transition-colors duration-200 font-medium text-sm"
            >
              &larr; Back to Home
            </Link>
          </div>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
